version: '3'
services: 
  web:
    build: ./web
    image: web/nginx_php7:1.0
    tty: true
    volumes:
      - ./web/app:/var/www/html/app.dev
    ports:
      - '8888:80'
    links:
      - db
      - cache
    depends_on:
      - db
      - cache
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: app
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: 123456
    volumes:
      - ./db/data:/var/lib/mysql
  cache:
    build: ./cache
    image: redis
    volumes:
      - ./cache/data:/data